[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
regex = "1.12.2"
rstest = "0.26.1"
good_lp = { version = "1.7", default-features = false, features = ["minilp"] }
